### ISSUE TITLE
Seems not working with profile fields of profile-manager

### ISSUE THREAD

**Issue by nobody000** [iionly/extended_tinymce#1]
Hi,
Thanks for this plugin, but I encounter a little problem.
The fields managed by plugin profile manager can't be updated. 

The old content of the field is well displayed but the updates of the text are not registered in data base.
Do you have any idea about this ?

Thank you very much.
Fred.

Elgg-1.10.5
Profile manager 9.01

**Comment by iionly** [comment]
Thanks for reporting. Unfortunately, I don't have any solution yet. I guess it's the same problem occuring when using the Group Tools plugin (also from Coldtrick) on Elgg 1.9 or later. There's something not working correctly when Tinymce is used either due to more than a single longtext input field used on a single page or maybe due to usage of the "hidden" attribute or maybe due to some JS issue. Both Profile Manager and Group Tools work fine with the Extended Tinymce plugin on Elgg 1.8 but for some reason I wasn't able to figure out yet it doesn't work anymore on Elgg 1.9 or later. It might be due to Elgg, the other plugins or due to a slightly different initialization of Tinymce (necessary on Elgg 1.9 or newer) that it gives problems.

If I figure out what's the problem I try to fix it for sure. But I can't say when I can fix it - as I'm currently really at a loss with this issue...

**Comment by nobody000** [comment]
A big thanks for your quick answer. I understand that it is not easy when working with plugins from different persons. 
I'll follow this thread and will see if you find a solution. But no hurry, elgg is furnished with a simple editor, so I can wait.
Regards
Fred.

**Comment by iionly** [comment]
Fixed in release 4.1.10 of Extended Tinymce.
