### ISSUE TITLE
Embed content hyperlink is inserted twice

### ISSUE THREAD

**Issue by oseg** [iionly/extended_tinymce#11]
Context: elgg v2.3.7+embed plugin enabled+extended_tinymce v4.7.9-elgg2.3

Scenario:
- Click on "Add a page" button to create a new page either in a group or in a user profile (does not matter)
- Enter a 'page title'
- Click on "Embed content" hyperlink
- Select 'Upload a file' tab in 'Embed content' popup
- Select a file, enter a 'file title'
- Scroll down 'Embed content' popup and click 'save' button
=> 'Your file was successfully saved" message is displayed & 'file title' is added in the 'files' tab
- In 'Embed content' 'files' tab, select 'file title'
=> The file hyperlink is inserted twice in the page

I checked previous releases: it seems to be a regression introduced by v4.7.9-2, The issue is not reproduced by versions: v4.7.1-2, v4.6.5-2 & v4.5.2-2.

**Comment by iionly** [comment]
I can reproduce it. The change after v4.7.1-2 was due to https://github.com/iionly/extended_tinymce/issues/8.

It seems a solution that works (but I currently have NO IDEA WHY!!!) would be to drop the lines
```
require(['elgg/embed'], function () {
	elgg.register_hook_handler('embed', 'editor', function(hook, type, params, value) {
		if (window.tinymce) {
			var editor = window.tinymce.get(params.textAreaId);
			if (editor) {
				var content = params.content;
				try {
					editor.insertContent(content);
					return false;
				} finally {
				}
			}
		}
	});
}, function (err) {
});
```
completely from mod/extended_tinymce/views/default/extended_tinymce/init.php. The Embed plugin deals with adding the embed content to the textarea content on its own if no plugin hook callback is registered to deal with it. Maybe the Tinymce editor can deal with it in the meantime this way while it surely wasn't possible in the past (or the callback wouldn't have been added in the first place back in Elgg 1.x days and such a callback is also used in the CKEdtior plugin even now...).

Could you test if it works for you, too, with the plugin hook callback lines removed? I don't fully trust this "solution" yet. Need to do some more testing tomorrow myself, too.

**Comment by oseg** [comment]
Yes it works without those lines, but I agree it's weird...

**Comment by oseg** [comment]
I found the root cause, the 'extended_tinymce/init.php' view is called as many times as the long text view is displayed.

In the above scenario, it happened twice:
1- in the 'add a page'
2- in the 'embed content' 'upload a file' popup

And then the hook is registered as many times as the long text view is displayed

**Comment by oseg** [comment]
And, if we don't register the hook, the file hyperlink is added by the embed plugin because of the 'selectionStart' property: same behavior as CKEditor.

**Comment by iionly** [comment]
As it seems it doesn't even fully work without the hook registered in init.php. Most likely it works if you alter the posting after embedding before submitting but if you try to submit a posting that only contains an embed link it fails (while the content area of the tinymce editor shows the embedding object the area element has been altered without tinymce knowing about it and therefore blocks the submit because it thinks it's an empty message). That's why the hook was introduced. With the embed plugin alone it would likely work fine on non-longtext fields. But the richtext editors work differently. They don't work on the original element but on their own internal element. Only on submit they would copy back the content of their internal element to the original element. With the tinymce editor I make sure this happens by using the tinymce triggerSave() method. That would be only thing necessary to do after Elgg (the embed plugin) would add the embed link to the content element on its own. Unfortunately, the Elgg plugin hook is triggered before the embed plugin alters the content. If the trigger would happen afterwards (or a second trigger would be available afterwards), the only job to do would be a triggerSave() of tinymce. Then it wouldn't matter if this would happen more than once either because the actual change of the content would only happen once.

Yep, the plugin hook callback that deals with the embedding is registered more than once. This might not even be a problem in all cases (as it hadn't been in the older versions). The problem might be that I now do the initialization of the editor in the same way regardless if the editor is displayed on a normal page or an ajax-served page. In the older versions of Extended Tinymce this was done in two different ways. And I think the problem right now is the longtext input within the file upload form when uploading a new item instead of selecting just an already available item to be embedded. The form is served by ajax so this seems to cause the duplicate triggering of the plugin hook callback (or even more than twice when repeating the uploading+embedding process).

I need to figure out how to fix it. I wonder why it works with CKeditor. It seems to be done in the same way there but maybe the little differences are what matters.

**Comment by iionly** [comment]
I hope I got it working with the changes in release 4.7.13.
