### ISSUE TITLE
tinymce list styles (list-style-type for instance) are not applied in elgg content (comment, pages, blog...)

### ISSUE THREAD

**Issue by oseg** [iionly/extended_tinymce#4]
Context: elgg v1.12.14 & extended_tinymce v4.4.0

I did a small test with different list-style-types (disc, circle and square) and I noticed :
- Tinymce editor styles are correct in the editor (edit mode)
- Styles are correct in the email notifications (with HTML_email_handler v3.1.1plugin enabled)
- But styles are not correct once content is published: list-style-type is disc for all
  - It seems like applied styles are those of the CKEditor...  however CKEditor plugin is disabled

A few hypothesis:
- Is the theme plugin (aalborg) interfering? I disabled aalborg plugin, but it did not change the list styles
- Should the extended_tinymce plugin set the .elgg-output ul ... styles? the tiny mce editor list styles seems defined in a plugin.min.js file (extended_tinymce/vendor/tinymce/js/tinymce/plugins/advlist)

**Comment by iionly** [comment]
The problem is that htmlawed filters out the list-style-types attributes from the postings when saving. It's not a matter of missing/wrong CSS or another plugin (apart from htmlawed) interferring. After the saving is done, the posting conten won't have the style information anymore.

It might be possible to keep the style information by modifying the htmlawed filter config. One problem is that the htmlawed plugin of Elgg doesn't use the full cofiguration capabilities htmlawed would offer in theory (mainly: it doesn't use the "spec" array parameter when calling htmlawed for filtering). Therefore, the configuration options are slightly limited (if you want to keep the filtering secure).

I've been looking for options how to keep more style information in the posting after saving (as long as they are safe) but so far I haven't found a working solution yet.

**Comment by iionly** [comment]
Got the thing with the list style working! It was possible to allow different styles to go through htmlawed by adding 'list-style-type' to the allowed styles in the extended_tinymce_allowed_styles() function in start.php of the Extended Tinymce plugin.

I'll add this change in the next release of the Extended Tinymce plugin (which I had planned to do since quite some time already but never had the time to do so...).

**Comment by oseg** [comment]
Thanks for your reactivity. We will wait for your next release.
Best regards,
Olivier

**Comment by oseg** [comment]
By the way, I still reproduce the issue even if I deactivate HTMLawed plugin...

**Comment by iionly** [comment]
Have you tested with a new post with a list after disabling the htmlawed plugin? For existing posts it won't help because the html style info not allowed is already removed when saving a post. So, for existing posts disabling htmlawed won't help. I also can't restore the style info with a new version of extended tinymce for existing posts. I should only prevent the removal of the list style tag on future posts made with the new version.

**Comment by oseg** [comment]
I tried with a fresh install of elgg 2.3.0 in a local environment (xampp), I disabled both CKEditor and HTMLawed plugins, I installed and enabled Extended-tinymce plugin v4.4.0.

Then I added a new page, wrote the following content in the page text field (Tinymce editor)

- level 1
  - level 2
    - level 3

And click on the save button to publish.

I still reproduce the issue.

**Comment by iionly** [comment]
With nested lists it seems there's a bug in the tinymce editor itself. While the list style looks visibly different in the editor before posting when increasing the indention the actual underlying html code has no list style attibutes at all. Only if you explicitly select a list style for a line in the list the style attibutes appear in the html code of the posting and then also are preserved when saving the post. I'm afraid I can't do anything here. It would be a matter of the tinymce editor developers to fix this.

Then only thing I can influence is that the list style info is preserved on saving (hopefully new version released this weekend).

**Comment by iionly** [comment]
New versions (4.5.2-1 for Elgg 1.9-2.2 and 4.5.2-2 for Elgg 2.3) released that won't filter out list-style attributes. The nested lists issue is a matter for the Tinymce editor developers hopefully dealt with in a future version soon.

**Comment by oseg** [comment]
But if it is a bug in Tinymce editor, why is it working fine with HTML_email_handler?

**Comment by iionly** [comment]
I think we might talk about two different issues. Have you tried the new release of Extended Tinymce yet? Does it still behave differently when posting a page and with HTML_email_handler when you create the nested list in the same manner? Or even try with creating several lists with different bullets styles each. With the new release the list style should remain within the post after saving. My guess is that HTML_email_handler might accept input not filtered by htmlawed and therefore the list style was kept already with the old version of Extended Tinymce.

But I've noticed that when I create a nested list by first creating the list items and then indenting the existing items to different list levels I see in the editor area different bullet styles used for the different levels but when displaying the html code of the message (as admin before posting the message) the html code does NOT contain any list styles for the nested levels of the list. So, there's no list style before saving and therefore also no list style after saving. But when I select different bullets styles manually for the list items (even if they seem to have these styles already) the html code of the message also contains the list style attributes and these are then also kept on saving the message. And this issue - difference between what is shown in wysiwyg mode and html code mode - is the bug in the tinymce editor I'm referring to.

**Comment by oseg** [comment]
Dear iionly,

I found out why I always have the same list-style-type even after deactivating HTMLawed and independently of extended_tinymce plugin versions (4.4.0 & 4.5.2-1):

I used the default bullet list style, which is represented inside the tinymce editor as:
- level 1
  - level 2
    - level 3

But once saved, this content have a different layout according to what is defined in aalborg plugin (or any other theme plugin) in typography.php:
```
.elgg-output ul, .elgg-output ol {
	margin: 0 1.5em 1.5em 0;
	padding-left: 1.5em;
}
.elgg-output ul {
	list-style-type: disc;
}
.elgg-output ol {
	list-style-type: decimal;
	list-style-position: inside;
	padding-left: .4em;
}
```
I had to add these css lines to have the same default layout between inside and outside tinymce editor:
```
.elgg-output ul ul {
	list-style-type: circle;
}
.elgg-output ul ul ul {
	list-style-type: square;
}
```
I will probably also have to increase the padding-left. I wonder if we should have this kind of CSS definitions in the extended_tinymce plugin ?

By the way, I also tested your latest version (4.5.2-1), it is working fine even when I choose a specific bullet list type (disc, circle, square). Thank you for the plugin update !

Olivier

**Comment by iionly** [comment]
Your observation that the list style is not preserved when only indenting a list item and not selecting a specific list style for this item additionally is exactly what I mean when saying that I think there's a bug in the tinymce editor code itself. The editor shows you different bullet styles in the editor before saving if you indent an item but the editor does NOT set the list-style-type accordingly. Therefore, you don't see the bullet style you were expecting after saving.

I don't think that it should be necessary to define the list style in CSS because if the tinymce editor would save a nested list correctly with the styles it showed you before saving the CSS definitions wouldn't be necessary in the first place. Nonetheless, adding a default in CSS for the list styles as fallback could make sense as I don't know when (and if at all) tinymce might come up with a fix.

In the meantime, you can always set the bullet style explicitely (in addition to only indenting a list item). Then the list style type will be set and preserved when saving.
