### ISSUE TITLE
lightgray skin regression introduced in release v4.7.1

### ISSUE THREAD

**Issue by oseg** [iionly/extended_tinymce#9]
Context: elgg v2.3.3 + extended_tinymce v4.7.9-2

The usual grey panel is now white (see screenshot below)

Issue reproduced in  v4.7.1-2
Issue NOT reproduced in v4.6.5-2

![image](https://user-images.githubusercontent.com/15892521/37520214-76f4de90-291c-11e8-8c59-a1f5bbdaf744.png)

**Comment by oseg** [comment]
To workaround the issue, download the lightgray skin at http://skin.tinymce.com/

And follow the instructions to create your own custom skin in the README of this plugin

**Comment by iionly** [comment]
Not a regression.

Moxiecode changed the look of the skin of the tinymce editor with the 4.7.0 release (from the changelog: "Updated the default skin to be more modern and white since white is preferred by most implementations."). I just bundle the default skin as it comes with the tinymce releases (only changes necessary are z-index adjustments for fullscreen mode and a workaround for the right border to be correctly displayed due to a bug in the editor code - bug reported since a while but not fixed).

I won't change the skin. Instructions how to change the skin are already included in the readme.

**Comment by oseg** [comment]
Thanks for the explanation
